export const FETCH_FAVOURITE_COURSE_REQUEST = 'FETCH_FAVOURITE_COURSE_REQUEST';
export const FETCH_FAVOURITE_COURSE_SUCCESS = 'FETCH_FAVOURITE_COURSE_SUCCESS';
export const FETCH_FAVOURITE_COURSE_FAILURE = 'FETCH_FAVOURITE_COURSE_FAILURE';
export const REMOVE_COURSE_FROM_FAVOURITE = 'REMOVE_COURSE_FROM_FAVOURITE';
export const ADD_COURSE_TO_FAVOURITE = 'ADD_COURSE_TO_FAVOURITE';
