export const FETCH_AUTHOR_COURSES_REQUEST = 'FETCH_AUTHOR_COURSES_REQUEST';
export const FETCH_AUTHOR_COURSES_SUCCESS = 'FETCH_AUTHOR_COURSES_SUCCESS';
export const FETCH_AUTHOR_COURSES_FAILURE = 'FETCH_AUTHOR_COURSES_FAILURE';
